server:
  port: 9000
  servlet:
    context-path: /api/spring

spring:
  profiles:
    active: hom

---
spring:
  config:
    activate:
      on-profile: dev
  app:
    name: "<h1 style=\"color: black; font-size: 40px; font: cursive;\">Utilizando o application.yaml, ambiente: development! </h1>"

---
spring:
  config:
    activate:
      on-profile: prod
  app:
    name: "<h1 style=\"color: black; font-size: 40px; font: cursive;\">Utilizando o application.yaml, ambiente: production! </h1>"

---
spring:
  config:
    activate:
      on-profile: hom
  app:
    name: "<h1 style=\"color: black; font-size: 40px; font: cursive;\">Utilizando o application.yaml, ambiente: staging! </h1>"