spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2